### ISSUE TITLE
New lab id not updated in OpenedX Ginkgo version

### ISSUE THREAD

**Issue by madhavipuliraju** [vlabs-on-openedx/open-edx-single-board-heater-system-simulation-virtual-lab-iitb#1]
New lab id not updated in OpenedX Ginkgo version

**Comment by sanchita-dixit** [comment]
Updated the new lab id in the Ginkgo version. @kraghupathi has to delete the older ported lab with older ID (ee32-iitb).

**Comment by sivashankerN** [comment]
Course "ee32-iitb" has been deleted from openedx-platform as the course created with proper lab_id(ee32).

Used following command(s) to delete the course
 >cd /edx/app/edxapp/edx-platform/
>sudo -u www-data /edx/bin/python.edxapp ./manage.py cms --settings=aws delete_course course-v1:Virtual-Labs+ee32-iitb+Anytime

**Comment by sivashankerN** [comment]
Miss configuration of experiment "Conducting Step Test simulation".  This page was not able to open in the browser, so not able to edit that experiment. Whoever ported this lab, they kept it as without editing experiment.

Then, Created new subsection. added all the experiment related info in the html editor. checked Lab_id and exp_id  as well for this experiment.

now we are able to edit the html file.

**Comment by sravanthimodepu** [comment]
Closing the issue, as all the ids are updated correctly.
